name: Build ImmortalWrt for Sony VPCX118LC
on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-24.10
  CONFIG_FILE: .config
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -y install build-essential clang flex bison g++ gawk gcc-multilib git libncurses-dev libssl-dev python3 rsync unzip zlib1g-dev

      - name: Clone ImmortalWrt code
        run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH immortalwrt

      - name: Apply custom config
        run: |
          cp .config immortalwrt/

      - name: Update feeds
        run: |
          cd immortalwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig

      - name: Compile firmware
        run: |
          cd immortalwrt
          make -j$(nproc) || make -j1 V=s

      - name: Show built files
        run: ls -lh immortalwrt/bin/targets/x86/generic/

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-firmware
          path: immortalwrt/bin/targets/x86/generic/*.img.gz
